package com.hzbhd.canbus.adapter.util;

import android.content.ComponentName;
import com.hzbhd.config.constant.ClassName;
import com.hzbhd.config.constant.PackageName;

/* loaded from: classes.dex */
public class HzbhdComponentName {
    public static final ComponentName ANDROID_SETTINGS;
    public static final ComponentName Apkinstaller;
    public static final ComponentName AppIconPicker;
    public static final ComponentName AtvMainActivity;
    public static final ComponentName AuxMainActivity;
    public static final ComponentName BHDSpeech;
    public static final ComponentName BLinkAAuto;
    public static final ComponentName BLinkCarPlay;
    public static final ComponentName BLinkDZMain;
    public static final ComponentName BLinkMain;
    public static final ComponentName CalCulaTor;
    public static final ComponentName Calendar;
    public static final ComponentName CanBusAirInfoCanbusAirService;
    public static final ComponentName CanbusCarInfoMainActivity;
    public static final ComponentName CanbusCarInfoService;
    public static final ComponentName CanbusRadarService;
    public static final ComponentName CarLogoSelect;
    public static final ComponentName CartSettings_AppIconPicker;
    public static final ComponentName ColorLedPaletteActivity;
    public static final ComponentName ColorMainActivity;
    public static final ComponentName DABRadioActivity;
    public static final ComponentName DTVMainActivity;
    public static final ComponentName DabMainActivity;
    public static final ComponentName DeskClock;
    public static final ComponentName Disc;
    public static final ComponentName DspMainActivity;
    public static final ComponentName DualZoneActivityNew;
    public static final ComponentName DvrAndroid;
    public static final ComponentName DvrCameraActivity;
    public static final ComponentName DvrHzbhd;
    public static final ComponentName DvrMainActivity;
    public static final ComponentName ES_FILEEXPLORERACTIVITY;
    public static final ComponentName EXPLORER_APP;
    public static final ComponentName EasyConnectyActivity;
    public static final ComponentName ExternalCameraMainActivity;
    public static final ComponentName FordEdgeTouchActivity;
    public static final ComponentName FordEdgeTouchActivityHiworld;
    public static final ComponentName FordEdgeTouchActivityNew;
    public static final ComponentName FordMondeoTouchActivityHiworld;
    public static final ComponentName FordRaiseAirActivity;
    public static final ComponentName FordSmaxTouchActivity;
    public static final ComponentName FordSyncActivity;
    public static final ComponentName GOOGLE_CHROME;
    public static final ComponentName GOOGLE_EMAIL;
    public static final ComponentName GOOGLE_MAPS;
    public static final ComponentName GaoDeMap;
    public static final ComponentName GmOnStarActivity;
    public static final ComponentName GmOnStarPhoneActivity;
    public static final ComponentName GmTouchActivity;
    public static final ComponentName GmTouchActivityNew;
    public static final ComponentName GmcOnstarAudioOnlyActivity;
    public static final ComponentName GocReceiver;
    public static final ComponentName GoogleVoiceSearch;
    public static final ComponentName Gpstestplus;
    public static final ComponentName HARVAL_H3_SIMPLE_TouchActivity;
    public static final ComponentName HandBook;
    public static final ComponentName HandBook_xph;
    public static final ComponentName HondaCarDeviceActivity;
    public static final ComponentName HondaCarRadioActivity;
    public static final ComponentName HondaCivicGeneralAirInfoActivity;
    public static final ComponentName HondaDaSimpleAirInfoActivity;
    public static final ComponentName JeepCanbusCDInfoActivity;
    public static final ComponentName JeepRaiseTouchActivity;
    public static final ComponentName JeepTouchActivity;
    public static final ComponentName KuWo;
    public static final ComponentName Launcher_Fast_Charging;
    public static final String MISC = "com.hzbhd.misc";
    public static final ComponentName MazdaCDdeviceActivity;
    public static final ComponentName MazdaOldRaisePhoneAudioActivity;
    public static final ComponentName MediaImage;
    public static final ComponentName MediaMusic;
    public static final ComponentName MediaVideo;
    public static final ComponentName MiddleCameraMainActivity;
    public static final ComponentName MzdCanbusCDInfoActivity;
    public static final ComponentName NAVI;
    public static final ComponentName NAVI2;
    public static final ComponentName NETFLIX;
    public static final ComponentName NewLauncher;
    public static final ComponentName NissanCamera360Activity;
    public static final ComponentName OnPauseOnResumeService;
    public static final ComponentName OneClickRepairActivity;
    public static final ComponentName OriginalScareenService;
    public static final ComponentName PA6CanbusSettingActivity;
    public static final ComponentName PA6CanbusSettingActivity291;
    public static final ComponentName PA6MeterActivity;
    public static final ComponentName PA6NaviActivity;
    public static final ComponentName PA6SAirActivity;
    public static final ComponentName PA6SAirActivity291;
    public static final ComponentName PA6SAirCleanActivity;
    public static final ComponentName PA6SettingActivity;
    public static final ComponentName PA6SmartSettingActivity;
    public static final ComponentName PC6InstrumentActivity;
    public static final ComponentName PC6SmartSettingActivity;
    public static final ComponentName PLAYSTORE_APP;
    public static final ComponentName PreCameraMainActivity;
    public static final ComponentName PreInstallHandBook;
    public static final ComponentName PsaTouchActivity;
    public static final ComponentName QzEnterCarActivity;
    public static final ComponentName QzRadioActivity;
    public static final ComponentName RadioActivity;
    public static final ComponentName RecentMainActivity;
    public static final ComponentName SBC;
    public static final ComponentName SOUGOU_BROWSER;
    public static final ComponentName SWC_APP;
    public static final ComponentName SYSTEMTIMESETACTIVITY2;
    public static final ComponentName ScannerRunService;
    public static final ComponentName SelectUiActivity;
    public static final ComponentName Settings$BodaFactoryTouchLearningStep1Activity;
    public static final ComponentName SettingsAppWidgetProvider;
    public static final ComponentName SoundRecorder;
    public static final ComponentName SpeechBoot;
    public static final ComponentName SpeechRecognition;
    public static final ComponentName Speechlyra;
    public static final ComponentName Spotify;
    public static final ComponentName SystemTimeSetActivity;
    public static final ComponentName SystemuiCanbusAirService;
    public static final ComponentName TOYOTA_RAISE_BinaryTouchActivity;
    public static final ComponentName TTMAppIconPicker;
    public static final ComponentName TXZADAPTER;
    public static final ComponentName TXZWAKEUP;
    public static final ComponentName TakeScreenshotService;
    public static final ComponentName ThrumpchiTouchActivity;
    public static final ComponentName Torque;
    public static final ComponentName ToyotaRaiseAirInfoActivity;
    public static final ComponentName TpmsoroBootCompleteReceiver;
    public static final ComponentName TpmsoroMainActivity;
    public static final ComponentName TpmsoroTpmsService;
    public static final ComponentName UPDProgressActivity;
    public static final ComponentName VolumeService;
    public static final ComponentName WAZE;
    public static final ComponentName YOUTUBE;
    public static final ComponentName ZlinkActivity;
    public static final ComponentName canGyroInfoActivity;
    public static final ComponentName[] canbus_old_devices;
    public static final ComponentName nissanCarDeviceActivity;
    public static final ComponentName psaRaiseComponetName;
    public static final ComponentName shell;
    public static final ComponentName CanBusDriveDataActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.activity.DriveDataActivity");
    public static final ComponentName CanBusService = new ComponentName("com.hzbhd.canbus", ClassName.bhd_service_canbus);
    public static final ComponentName NewCanBusMainActivity = new ComponentName("com.hzbhd.canbus", ClassName.bhd_canbus);
    public static final ComponentName NewCanBusOriginalCarDeviceActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.activity.OriginalCarDeviceActivity");
    public static final ComponentName SelectCanTypeActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.activity.SelectCanTypeActivity");
    public static final ComponentName CanBusAirActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.activity.AirActivity");
    public static final ComponentName NewCanbusOnStarActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.activity.OnStarActivity");
    public static final ComponentName CanbusTireInfoActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.activity.TirePressureActivity");
    public static final ComponentName NewCanbusSyncActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.activity.SyncActivity");
    public static final ComponentName NewCanbusSettingActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.activity.SettingActivity");
    public static final ComponentName YuanYiYuanAirActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.car_cus._304.activity.AirActivity");
    public static final ComponentName YuanYiYuanMainActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.car_cus._304.activity.MainActivity");
    public static final ComponentName OriginalMediaActivity_LEXUS = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.car_cus._451.activity.lexus.OriginalMediaActivity");
    public static final ComponentName Aux2Activity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.media.aux2.activity.Aux2Activity");
    public static final ComponentName AirActivity460 = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus._460.activity.AirActivity460");
    public static final ComponentName CarBodyActivityD1 = new ComponentName("com.hzbhd.canbus", ClassName.d1CanBus);
    public static final ComponentName AvmActivityD1 = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus._462.activity.AvmActivityD1");
    public static final ComponentName CarBodyActivityE1 = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus._471.activity.CarBodyActivityE1");
    public static final ComponentName CarBodyActivityA3 = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus._473.activity.CarBodyActivityA3");
    public static final ComponentName ID439MainActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.car_cus._439.activity.ID439MainActivity");
    public static final ComponentName ID439MainActivity1280x720 = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.car_cus._467.activity.ID439MainActivity");
    public static final ComponentName ID439PanelActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.car_cus._439.activity.ID439PanelActivity");
    public static final ComponentName ID439PanelActivity1280x720 = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.car_cus._467.activity.ID439PanelActivity");
    public static final ComponentName Id324AuxVideoActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.car._324.Id324AuxVideoActivity");
    public static final ComponentName SettingsActivity466 = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus._466.activity.SettingsGroup0x00Activity466");
    public static final ComponentName AccessoryControlActivity466 = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus._466.activity.AccessoryControlActivity466");
    public static final ComponentName DriveActivity466 = new ComponentName("com.hzbhd.canbus", ClassName.MotorcycleInformation);
    public static final ComponentName GaugesActivity466 = new ComponentName("com.hzbhd.canbus", ClassName.instrument);
    public static final ComponentName SettingActivity460 = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus._460.activity.SettingActivity460");
    public static final ComponentName CanBusOnlineUpdateActivity = new ComponentName(PackageName.bhd_ui_upgrade, "com.hzbhd.client.upgrade.activity.MainActivity");
    public static final ComponentName WmCarSettings = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.car_cus._446.activity.WmCarSettingActivity");
    public static final ComponentName SldDvrActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.car_cus._448.activity.DvrActivity");
    public static final ComponentName MsRadarActivity = new ComponentName(PackageName.bhd_ui_settings, "com.hzbhd.ui.config.ui_l9.activity.MsRadarActivity");
    public static final ComponentName BlueTeethActivity = new ComponentName(CrashReportUtils.PACKAGENAME_BLUETOOTH, "com.hzbhd.bluetooth.hfp.HfpMainActivity");
    public static final ComponentName A2dpActivity = new ComponentName(CrashReportUtils.PACKAGENAME_BLUETOOTH, "com.hzbhd.bluetooth.a2dp.A2dpMainActivity");
    public static final ComponentName BubbleCall = new ComponentName(CrashReportUtils.PACKAGENAME_BLUETOOTH, "com.hzbhd.bluetooth.call.BubbleCall");

    static {
        ComponentName componentName = new ComponentName("com.hzbhd.canbusairinfo", "com.hzbhd.canbusairinfo.activity.FordSmaxTouchActivity");
        FordSmaxTouchActivity = componentName;
        ComponentName componentName2 = new ComponentName("com.hzbhd.canbusairinfo", "com.hzbhd.canbusairinfo.activity.JeepTouchActivity");
        JeepTouchActivity = componentName2;
        ComponentName componentName3 = new ComponentName("com.hzbhd.canbusairinfo", "com.hzbhd.canbusairinfo.activity.GmTouchActivity");
        GmTouchActivity = componentName3;
        ComponentName componentName4 = new ComponentName("com.hzbhd.canbusairinfo", "com.hzbhd.canbusairinfo.activity.FordEdgeTouchActivity");
        FordEdgeTouchActivity = componentName4;
        ComponentName componentName5 = new ComponentName("com.hzbhd.canbusairinfo", "com.hzbhd.canbusairinfo.activity.GmTouchActivityNew");
        GmTouchActivityNew = componentName5;
        ComponentName componentName6 = new ComponentName("com.hzbhd.canbusairinfo", "com.hzbhd.canbusairinfo.activity.NissanCamera360Activity");
        NissanCamera360Activity = componentName6;
        ComponentName componentName7 = new ComponentName("com.hzbhd.canbusairinfo", "com.hzbhd.canbusairinfo.activity.FordEdgeTouchActivityNew");
        FordEdgeTouchActivityNew = componentName7;
        CanBusAirInfoCanbusAirService = new ComponentName("com.hzbhd.canbusairinfo", "com.hzbhd.canbusairinfo.CanbusAirService");
        ComponentName componentName8 = new ComponentName("com.hzbhd.canbusairinfo", "com.hzbhd.canbusairinfo.activity.PsaGeneralTouchActivity");
        psaRaiseComponetName = componentName8;
        ComponentName componentName9 = new ComponentName("com.hzbhd.canbusairinfo", "com.hzbhd.canbusairinfo.activity.PsaTouchActivity");
        PsaTouchActivity = componentName9;
        ComponentName componentName10 = new ComponentName("com.hzbhd.canbusairinfo", "com.hzbhd.canbusairinfo.activity.HARVAL_H3_SIMPLE_TouchActivity");
        HARVAL_H3_SIMPLE_TouchActivity = componentName10;
        ComponentName componentName11 = new ComponentName("com.hzbhd.canbusairinfo", "com.hzbhd.canbusairinfo.activity.FordEdgeTouchActivityHiworld");
        FordEdgeTouchActivityHiworld = componentName11;
        ComponentName componentName12 = new ComponentName("com.hzbhd.canbusairinfo", "com.hzbhd.canbusairinfo.activity.FordMondeoTouchActivityHiworld");
        FordMondeoTouchActivityHiworld = componentName12;
        ComponentName componentName13 = new ComponentName("com.hzbhd.canbusairinfo", "com.hzbhd.canbusairinfo.activity.ThrumpchiTouchActivity");
        ThrumpchiTouchActivity = componentName13;
        ComponentName componentName14 = new ComponentName("com.hzbhd.canbusairinfo", "com.hzbhd.canbusairinfo.activity.ToyotaRaiseGeneralDualAirInfoActivity");
        ToyotaRaiseAirInfoActivity = componentName14;
        ComponentName componentName15 = new ComponentName("com.hzbhd.canbusairinfo", "com.hzbhd.canbusairinfo.activity.toyotaRaiseBinaryTouchActivity");
        TOYOTA_RAISE_BinaryTouchActivity = componentName15;
        ComponentName componentName16 = new ComponentName("com.hzbhd.canbusairinfo", "com.hzbhd.canbusairinfo.activity.JeepRaiseTouchActivity");
        JeepRaiseTouchActivity = componentName16;
        ComponentName componentName17 = new ComponentName("com.hzbhd.canbusairinfo", "com.hzbhd.canbusairinfo.activity.HondaDaSimpleAirInfoActivity");
        HondaDaSimpleAirInfoActivity = componentName17;
        ComponentName componentName18 = new ComponentName("com.hzbhd.canbusairinfo", "com.hzbhd.canbusairinfo.activity.HondaCivicGeneralAirInfoActivity");
        HondaCivicGeneralAirInfoActivity = componentName18;
        ComponentName componentName19 = new ComponentName("com.hzbhd.canbusairinfo", "com.hzbhd.canbusairinfo.activity.FordRaiseAirActivity");
        FordRaiseAirActivity = componentName19;
        ComponentName componentName20 = new ComponentName("com.hzbhd.canbuscarinfo", "com.hzbhd.canbuscarinfo.ui.jeepcarinfo.JeepCanbusCDInfoActivity");
        JeepCanbusCDInfoActivity = componentName20;
        ComponentName componentName21 = new ComponentName("com.hzbhd.canbuscarinfo", "com.hzbhd.canbuscarinfo.ui.mzd.mazda3_mazda6_2017.MzdCanbusCDInfoActivity");
        MzdCanbusCDInfoActivity = componentName21;
        ComponentName componentName22 = new ComponentName("com.hzbhd.canbuscarinfo", "com.hzbhd.canbuscarinfo.ui.fordcarinfo.FordSyncActivity");
        FordSyncActivity = componentName22;
        ComponentName componentName23 = new ComponentName("com.hzbhd.canbuscarinfo", "com.hzbhd.canbuscarinfo.ui.gmcarinfo.GmOnStarActivity");
        GmOnStarActivity = componentName23;
        ComponentName componentName24 = new ComponentName("com.hzbhd.canbuscarinfo", "com.hzbhd.canbuscarinfo.ui.gmcarinfo.GmcOnstarAudioOnlyActivity");
        GmcOnstarAudioOnlyActivity = componentName24;
        ComponentName componentName25 = new ComponentName("com.hzbhd.canbuscarinfo", "com.hzbhd.canbuscarinfo.ui.hondacarinfo.HondaCarDeviceActivity");
        HondaCarDeviceActivity = componentName25;
        ComponentName componentName26 = new ComponentName("com.hzbhd.canbuscarinfo", "com.hzbhd.canbuscarinfo.ui.nissancarinfo.NissanCarDeviceActivity");
        nissanCarDeviceActivity = componentName26;
        ComponentName componentName27 = new ComponentName("com.hzbhd.canbuscarinfo", "com.hzbhd.canbuscarinfo.ui.jeepcarinfo.GyroInfoActivity");
        canGyroInfoActivity = componentName27;
        ComponentName componentName28 = new ComponentName("com.hzbhd.canbuscarinfo", "com.hzbhd.canbuscarinfo.ui.mzd.MazdaOldRaisePhoneAudioActivity");
        MazdaOldRaisePhoneAudioActivity = componentName28;
        ComponentName componentName29 = new ComponentName("com.hzbhd.canbuscarinfo", "com.hzbhd.canbuscarinfo.ui.qizhi.QzEnterCar");
        QzEnterCarActivity = componentName29;
        ComponentName componentName30 = new ComponentName("com.hzbhd.canbuscarinfo", "com.hzbhd.canbuscarinfo.ui.hondacarinfo.HondaCarRadioActivity");
        HondaCarRadioActivity = componentName30;
        CanbusCarInfoMainActivity = new ComponentName("com.hzbhd.canbuscarinfo", "com.hzbhd.canbuscarinfo.MainActivity");
        CanbusCarInfoService = new ComponentName("com.hzbhd.canbuscarinfo", "com.hzbhd.canbuscarinfo.CanbusCarInfoService");
        ComponentName componentName31 = new ComponentName("com.hzbhd.canbuscarinfo", "com.hzbhd.canbuscarinfo.baseSample.BaseSampleMazdaCDInfoActivity");
        MazdaCDdeviceActivity = componentName31;
        ComponentName componentName32 = new ComponentName("com.hzbhd.canbuscarinfo", "com.hzbhd.canbuscarinfo.ui.gmcarinfo.GmOnStarPhoneActivity");
        GmOnStarPhoneActivity = componentName32;
        CalCulaTor = new ComponentName(PackageName.android_calculator, ClassName.android_calculator);
        HandBook = new ComponentName(PackageName.bhd_handbook_hy, ClassName.bhd_hand_book_hy_f5);
        HandBook_xph = new ComponentName("com.hzbhd.handbooks.xph", ClassName.bhd_hand_book_hy_f5);
        PreInstallHandBook = new ComponentName("com.hzbhd.book", ClassName.bhd_hand_book_hy_f5);
        CarLogoSelect = new ComponentName("com.hzbhd.carlogoselect", "com.hzbhd.carlogoselect.CarLogoSelectActivity");
        MediaImage = new ComponentName(CrashReportUtils.PACKAGENAME_MEDIA, "com.hzbhd.media.Image");
        MediaMusic = new ComponentName(CrashReportUtils.PACKAGENAME_MEDIA, "com.hzbhd.media.Music");
        MediaVideo = new ComponentName(CrashReportUtils.PACKAGENAME_MEDIA, "com.hzbhd.media.Video");
        UPDProgressActivity = new ComponentName("com.hzbhd.upgrade", "com.hzbhd.upgrade.UPDProgressActivity");
        Settings$BodaFactoryTouchLearningStep1Activity = new ComponentName(CrashReportUtils.PACKAGENAME_SETTING, "com.android.settings.Settings$BodaFactoryTouchLearningStep1Activity");
        AppIconPicker = new ComponentName(CrashReportUtils.PACKAGENAME_SETTING, "com.android.settings.hzbhd.AppIconPicker");
        CartSettings_AppIconPicker = new ComponentName(PackageName.bhd_ui_settings, "com.android.settings.hzbhd.AppIconPicker");
        TTMAppIconPicker = new ComponentName(CrashReportUtils.PACKAGENAME_SETTING, "com.android.settings.hzbhd.TTMAppIconPicker");
        SettingsAppWidgetProvider = new ComponentName(CrashReportUtils.PACKAGENAME_SETTING, "com.android.settings.widget.SettingsAppWidgetProvider");
        SelectUiActivity = new ComponentName(MISC, "com.hzbhd.misc.select_ui.SelectUiActivity");
        AtvMainActivity = new ComponentName(MISC, "com.hzbhd.misc.atv.MainActivity");
        DTVMainActivity = new ComponentName(MISC, "com.hzbhd.misc.dtv.DTVMainActivity");
        DvrMainActivity = new ComponentName(MISC, "com.hzbhd.misc.dvr.MainActivity");
        PreCameraMainActivity = new ComponentName(MISC, "com.hzbhd.misc.camera.PreCameraActivity");
        MiddleCameraMainActivity = new ComponentName(MISC, "com.hzbhd.misc.camera.MiddleCameraActivity");
        AuxMainActivity = new ComponentName(MISC, "com.hzbhd.misc.auxin.MainActivity");
        VolumeService = new ComponentName(MISC, "com.hzbhd.misc.volume.VolumeService");
        CanbusRadarService = new ComponentName(MISC, "com.hzbhd.misc.park.CanbusRadarService");
        Launcher_Fast_Charging = new ComponentName(MISC, "com.hzbhd.misc.fast_charging.FastChargingActivity");
        OnPauseOnResumeService = new ComponentName(MISC, "com.hzbhd.misc.MiscTaskService");
        Calendar = new ComponentName("com.android.calendar", "com.android.calendar.AllInOneActivity");
        Disc = new ComponentName("com.hzbhd.disc", "com.hzbhd.disc.Disc");
        ColorMainActivity = new ComponentName("com.hzbhd.ColorLed", "com.hzbhd.ColorLed.MainActivity");
        DabMainActivity = new ComponentName("com.ex.dabplayer.pad", "com.ex.dabplayer.pad.activity.MainActivity");
        DABRadioActivity = new ComponentName(CrashReportUtils.PACKAGENAME_RADIO, "com.hzbhd.radio.dab.DabActivity");
        RadioActivity = new ComponentName(CrashReportUtils.PACKAGENAME_RADIO, "com.hzbhd.radio.MainActivity");
        DvrCameraActivity = new ComponentName("com.hzbhd.dvr", "com.hzbhd.dvr.CameraActivity");
        TpmsoroMainActivity = new ComponentName("com.hzbhd.tpmsoro", "com.hzbhd.tpmsoro.MainActivity");
        TpmsoroBootCompleteReceiver = new ComponentName("com.hzbhd.tpmsoro", "com.hzbhd.tpmsoro.BootCompleteReceiver");
        TpmsoroTpmsService = new ComponentName("com.hzbhd.tpmsoro", "com.hzbhd.tpmsoro.TpmsService");
        SoundRecorder = new ComponentName("com.android.soundrecorder", ClassName.android_soundRecorder);
        Torque = new ComponentName("org.prowl.torque", "org.prowl.torque.landing.FrontPage");
        DspMainActivity = new ComponentName(CrashReportUtils.PACKAGENAME_DSP, "com.hzbhd.dsp.DspActivity");
        RecentMainActivity = new ComponentName("com.android.systemui", "com.android.systemui.recents.RecentsActivity");
        EasyConnectyActivity = new ComponentName("net.easyconn", "net.easyconn.ui.MainActivity");
        DualZoneActivityNew = new ComponentName("com.hzbhd.backapp", "com.hzbhd.backapp.MainActivity");
        QzRadioActivity = new ComponentName(CrashReportUtils.PACKAGENAME_RADIO, "com.hzbhd.radio.MainActivity");
        GocReceiver = new ComponentName(PackageName.gocsdk, "com.goodocom.gocsdk.receiver.GocReceiver");
        TakeScreenshotService = new ComponentName("com.android.systemui", "com.android.systemui.screenshot.TakeScreenshotService");
        SystemuiCanbusAirService = new ComponentName("com.android.systemui", "com.android.systemui.hzbhd.CanbusAirService");
        ScannerRunService = new ComponentName(PackageName.bhd_scanner, "com.hzbhd.mediaScanner.service.RunService");
        OriginalScareenService = new ComponentName("com.android.launcher3", "com.android.launcher3.externalActivity.ReceiveDataService");
        NewLauncher = new ComponentName("com.android.launcher3", "com.android.launcher3.activity.MainActivity");
        EXPLORER_APP = new ComponentName(PackageName.esFile, ClassName.esFile);
        SWC_APP = new ComponentName(CrashReportUtils.PACKAGENAME_SWC, "com.hzbhd.swc.MainActivity");
        PLAYSTORE_APP = new ComponentName(PackageName.andriod_vending, ClassName.android_vending);
        GOOGLE_EMAIL = new ComponentName(PackageName.android_email, ClassName.android_email);
        GOOGLE_MAPS = new ComponentName(PackageName.google_map, ClassName.google_map);
        GOOGLE_CHROME = new ComponentName(PackageName.android_chrome, ClassName.google_chrome);
        ES_FILEEXPLORERACTIVITY = new ComponentName(PackageName.esFile, ClassName.esFile);
        TXZADAPTER = new ComponentName("com.txznet.smartadapter", ClassName.toppalVolceActivity);
        TXZWAKEUP = new ComponentName(PackageName.txz, "com.txznet.smartwakeup.receiver.BootCompletedReciver");
        BHDSpeech = new ComponentName(PackageName.bhd_speech, "com.hzbhd.speechrecognition.SpeechRecognitionActivity");
        ANDROID_SETTINGS = new ComponentName(CrashReportUtils.PACKAGENAME_SETTING, "com.android.settings.Settings");
        NAVI = new ComponentName("com.android.launcher3", "com.android.launcher3.activity.NaviActivity");
        NAVI2 = new ComponentName("com.android.launcher3", "com.android.launcher3.firstscreen.NaviActivity");
        ExternalCameraMainActivity = new ComponentName(MISC, "com.hzbhd.misc.camera.IrPanoramaCameraActivity");
        SystemTimeSetActivity = new ComponentName(CrashReportUtils.PACKAGENAME_SETTING, "com.android.settings.DateTimeSettingsActivity");
        SYSTEMTIMESETACTIVITY2 = new ComponentName(CrashReportUtils.PACKAGENAME_SETTING, "com.android.settings.Settings$DateTimeSettingsActivity");
        BLinkMain = new ComponentName("com.hzbhd.blink", "com.hzbhd.blink.WelcomeActivity");
        BLinkCarPlay = new ComponentName("com.hzbhd.blink", "com.hzbhd.blink.CarPlayActivity");
        BLinkAAuto = new ComponentName("com.hzbhd.blink", "com.hzbhd.blink.AndroidAutoActivty");
        BLinkDZMain = new ComponentName("com.hzbhd.blink", "com.hzbhd.blink.custom.DZCustomActivity");
        ColorLedPaletteActivity = new ComponentName("com.hzbhd.ColorLed", "com.hzbhd.multicolor.MulticolorActivity");
        ZlinkActivity = new ComponentName("com.zjinnova.zlink", "com.zjinnova.zlink.main.view.SplashActivity");
        PA6NaviActivity = new ComponentName("com.android.launcher3", "com.android.launcher3.firstscreen.NaviActivity");
        PA6SettingActivity = new ComponentName(CrashReportUtils.PACKAGENAME_SETTING, "com.android.settings.hzbhd.a6.A6SettingActivity");
        PA6CanbusSettingActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.car_cus._283.MainActivity");
        PA6SmartSettingActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.car_cus._283.smart.SmartPowerActivity");
        PA6SAirActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.car_cus._283.activity.AirActivity");
        PA6SAirCleanActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.car_cus._283.activity.AirCleanActivity");
        PA6MeterActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.car_cus._283.activity.MeterActivity");
        PA6CanbusSettingActivity291 = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.car_cus._291.MainActivity");
        PA6SAirActivity291 = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.car_cus._291.AirActivity");
        SpeechRecognition = new ComponentName(PackageName.bhd_speech, "com.hzbhd.speechrecognition.service.SpeechRecognitionService");
        Speechlyra = new ComponentName("com.aispeech.lyra.adapter", "com.aispeech.lyra.adapter.service.BodaService");
        SpeechBoot = new ComponentName(PackageName.bhd_midware, "com.hzbhd.midware.speechrecognition.BootSpeechService");
        PC6SmartSettingActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.car_cus._299.smart.SmartPowerActivity");
        PC6InstrumentActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.car_cus._299.instrument.InstrumentActivity");
        Spotify = new ComponentName(PackageName.spotify, ClassName.spotify);
        YOUTUBE = new ComponentName(PackageName.google_youtube, ClassName.google_youtube);
        NETFLIX = new ComponentName(PackageName.netflix, ClassName.netflix);
        WAZE = new ComponentName(PackageName.waze, ClassName.waze);
        SOUGOU_BROWSER = new ComponentName("sogou.mobile.explorer", "sogou.mobile.explorer.NoDisplayActivity");
        GaoDeMap = new ComponentName("com.autonavi.amapauto", "com.autonavi.auto.remote.fill.UsbFillActivity");
        KuWo = new ComponentName(PackageName.kuwo, ClassName.kuwo);
        DvrHzbhd = new ComponentName(PackageName.bhd_ui_settings, "com.android.settings.hzbhd.DvrAppIconPicker");
        DvrAndroid = new ComponentName(CrashReportUtils.PACKAGENAME_SETTING, "com.android.settings.hzbhd.DvrAppIconPicker");
        DeskClock = new ComponentName("com.android.deskclock", "com.android.deskclock.DeskClock");
        shell = new ComponentName("mww.androidterm", "jackpal.androidterm.Term");
        SBC = new ComponentName(PackageName.lyra_deamon, "com.aispeech.lyra.daemon.DaemonActivity");
        Apkinstaller = new ComponentName("com.android.apkinstaller", "com.android.apkinstaller.apkinstaller");
        Gpstestplus = new ComponentName(PackageName.gps_test, ClassName.gpsTest);
        GoogleVoiceSearch = new ComponentName(PackageName.google_search, "com.google.android.googlequicksearchbox.VoiceSearchActivity");
        OneClickRepairActivity = new ComponentName("com.hzbhd.canbus", "com.hzbhd.canbus.car_cus._439.activity.OneClickRepairActivity");
        canbus_old_devices = new ComponentName[]{componentName, componentName2, componentName3, componentName4, componentName5, componentName6, componentName7, componentName8, componentName9, componentName10, componentName11, componentName12, componentName13, componentName14, componentName15, componentName16, componentName17, componentName18, componentName20, componentName21, componentName22, componentName23, componentName24, componentName25, componentName26, componentName27, componentName28, componentName29, componentName30, componentName31, componentName32, componentName19};
    }
}
