package com.hzbhd.canbus.ui_datas;

import com.hzbhd.canbus.entity.OriginalCarDeviceUpdateEntity;
import com.hzbhd.canbus.entity.SongListEntity;
import java.util.List;

/* loaded from: classes2.dex */
public class GeneralOriginalCarDeviceData {
    public static boolean am_st = false;
    public static boolean auto_p = false;
    public static boolean auto_store = false;
    public static boolean aux_insert = false;
    public static boolean band = false;
    public static boolean cd = false;
    public static String cdStatus = null;
    public static String discStatus = null;
    public static boolean disc_scan = false;
    public static boolean down = false;
    public static boolean dvd = false;
    public static String endTime = "00:00";
    public static boolean exit_cd = false;
    public static boolean fold_add = false;
    public static boolean fold_sub = false;
    public static boolean folder = false;
    public static boolean insert = false;
    public static boolean isBottomBtnChange = true;
    public static boolean isSongListChange = true;
    public static boolean isTopBtnChange = true;
    public static boolean left = false;
    public static boolean lock = false;
    public static List<OriginalCarDeviceUpdateEntity> mList = null;
    public static boolean mp3 = false;
    public static boolean next_disc = false;
    public static boolean pause = false;
    public static boolean play = false;
    public static boolean play_pause = false;
    public static boolean power = false;
    public static boolean preset_scan = false;
    public static boolean preset_select = false;
    public static boolean preset_store = false;
    public static boolean prev_disc = false;
    public static int progress = 0;
    public static boolean radio = false;
    public static boolean radio_scan = false;
    public static boolean rdm = false;
    public static boolean rdm_disc = false;
    public static boolean rdm_fold = false;
    public static boolean rdm_off = false;
    public static boolean rds = false;
    public static boolean rear_cdc = false;
    public static boolean refresh = false;
    public static boolean right = false;
    public static boolean rpt = false;
    public static boolean rpt_disc = false;
    public static boolean rpt_fold = false;
    public static boolean rpt_off = false;
    public static boolean rpt_track = false;
    public static String runningState = null;
    public static boolean scan = false;
    public static boolean scane = false;
    public static boolean select_cd = false;
    public static List<SongListEntity> songList = null;
    public static boolean st = false;
    public static String startTime = "00:00";
    public static boolean up = false;
    public static boolean wma = false;
}
