package com.hzbhd.commontools;

import com.hzbhd.commontools.AppIdDef;
import com.hzbhd.config.constant.ClassName;
import com.hzbhd.config.constant.PackageName;
import java.util.HashMap;

/* loaded from: classes2.dex */
public class DefaultAppId {
    public static HashMap<AppIdDef.APP_ID, ComponentName> ui = new HashMap<AppIdDef.APP_ID, ComponentName>() { // from class: com.hzbhd.commontools.DefaultAppId.1
        {
            put(AppIdDef.APP_ID.BHD_NONE, new ComponentName("", ""));
            put(AppIdDef.APP_ID.BHD_UI_HDMI, new ComponentName(PackageName.bhd_ui_camera, ClassName.bhd_ui_hdmi));
            put(AppIdDef.APP_ID.BHD_UI_DTV, new ComponentName(PackageName.bhd_ui_camera, ClassName.bhd_ui_dtv));
            put(AppIdDef.APP_ID.BHD_UI_AUX, new ComponentName(PackageName.bhd_ui_camera, ClassName.bhd_ui_auxIn));
            put(AppIdDef.APP_ID.BHD_UI_DISC, new ComponentName(PackageName.bhd_ui_media, ClassName.bhd_ui_disc));
            put(AppIdDef.APP_ID.BHD_UI_F_CAMERA, new ComponentName(PackageName.bhd_ui_camera, ClassName.bhd_ui_fCamera));
            put(AppIdDef.APP_ID.BHD_UI_4_CAMERA, new ComponentName(PackageName.bhd_ui_camera, ClassName.bhd_ui_4Camera));
            put(AppIdDef.APP_ID.BHD_UI_LAUNCHER_NAVI, new ComponentName("com.android.launcher3", "com.android.launcher3.firstscreen.NaviActivity"));
            put(AppIdDef.APP_ID.BHD_UI_RADIO, new ComponentName(PackageName.bhd_ui_radio, ClassName.bhd_ui_radio));
            put(AppIdDef.APP_ID.BHD_UI_MUSIC, new ComponentName(PackageName.bhd_ui_media, ClassName.bhd_ui_music));
            put(AppIdDef.APP_ID.BHD_UI_VIDEO, new ComponentName(PackageName.bhd_ui_media, ClassName.bhd_ui_video));
            put(AppIdDef.APP_ID.BHD_UI_IMAGE, new ComponentName(PackageName.bhd_ui_media, ClassName.bhd_ui_image));
            put(AppIdDef.APP_ID.BHD_UI_BT_PHONE, new ComponentName(PackageName.bhd_ui_bt, ClassName.bhd_ui_btMain));
            put(AppIdDef.APP_ID.BHD_UI_BT_MUSIC, new ComponentName(PackageName.bhd_ui_bt, ClassName.bhd_ui_btAudio));
            put(AppIdDef.APP_ID.BHD_UI_BT_BUBBLE_CALL, new ComponentName(PackageName.bhd_ui_bt, ClassName.bhd_ui_btBubble));
            put(AppIdDef.APP_ID.BHD_UI_DSP, new ComponentName(PackageName.bhd_ui_dsp, ClassName.bhd_ui_dsp));
            put(AppIdDef.APP_ID.BHD_UI_DAB_HGJ, new ComponentName(PackageName.bhd_ui_dab_hgj, ClassName.bhd_ui_dab_hgj));
            put(AppIdDef.APP_ID.BHD_UI_DAB_YHX, new ComponentName(PackageName.bhd_ui_dab_yhx, ClassName.bhd_ui_dab_yhx));
            put(AppIdDef.APP_ID.BHD_UI_DAB_NX3K, new ComponentName(PackageName.bhd_ui_dab_nx3k, ClassName.bhd_ui_dab_nx3k));
            put(AppIdDef.APP_ID.BHD_UI_FAQ, new ComponentName(PackageName.bhd_handbook, "com.artifex.mupdfdemo.main.MuPDFActivity"));
            put(AppIdDef.APP_ID.BHD_UI_FAQ_HY, new ComponentName(PackageName.bhd_handbook_hy, "com.artifex.mupdfdemo.main.MuPDFActivity"));
            put(AppIdDef.APP_ID.BHD_UI_FAQ_HY_F5, new ComponentName(PackageName.bhd_handbook_hy, ClassName.bhd_hand_book_hy_f5));
            put(AppIdDef.APP_ID.BHD_UI_LINK, new ComponentName(PackageName.bhd_phonelink, "com.hzbhd.phonelink.WelcomeActivity"));
            put(AppIdDef.APP_ID.BHD_UI_CAN_BUS, new ComponentName("com.hzbhd.canbus", ClassName.bhd_canbus));
            put(AppIdDef.APP_ID.BHD_UI_SETTINGS, new ComponentName(PackageName.bhd_ui_settings, ClassName.bhd_ui_carSettings));
            put(AppIdDef.APP_ID.BHD_UI_MODEN_CALL, new ComponentName(PackageName.bhd_ui_moden_call, ClassName.bhd_ui_modencall));
            put(AppIdDef.APP_ID.BHD_UI_CARPLAY, new ComponentName(PackageName.bhd_phonelink, ClassName.bhd_phonelink_carplay));
            put(AppIdDef.APP_ID.BHD_UI_AUTO, new ComponentName(PackageName.bhd_phonelink, ClassName.bhd_phonelink_auto));
            put(AppIdDef.APP_ID.BHD_UI_CARPLAY_Not, new ComponentName(PackageName.bhd_phonelink, ClassName.bhd_phonelink_carplay_not_conn));
            put(AppIdDef.APP_ID.BHD_UI_AUTO_Not, new ComponentName(PackageName.bhd_phonelink, ClassName.bhd_phonelink_auto_not_conn));
            put(AppIdDef.APP_ID.BHD_UI_CONNECTIONS, new ComponentName(PackageName.bhd_phonelink, "com.hzbhd.phonelink.WelcomeActivity"));
            put(AppIdDef.APP_ID.BHD_UI_UPGRADE, new ComponentName(PackageName.bhd_system_upgrade, ClassName.bhd_system_upgrade));
            put(AppIdDef.APP_ID.WIRELESS_Q_LINK, new ComponentName(PackageName.bhd_wireless_q_link, ClassName.bhd_wireless_q_link));
            put(AppIdDef.APP_ID.BHD_UI_SIRIUS_XM, new ComponentName(PackageName.bhd_sirius_xm, ClassName.bhd_ui_sxm));
            put(AppIdDef.APP_ID.BHD_XYQ_AVM, new ComponentName(PackageName.bhd_xyq_avm, ClassName.bhd_xyq_avm));
            put(AppIdDef.APP_ID.BHD_XYQ_AVM_CAMERA4, new ComponentName(PackageName.bhd_xyq_avm, ClassName.bhd_xyq_avm_camera4));
            put(AppIdDef.APP_ID.AUTOCHIP_AVM, new ComponentName(PackageName.autochip_avm, ClassName.autochip_avm));
            put(AppIdDef.APP_ID.GOOGLE_MAP, new ComponentName(PackageName.google_map, ClassName.google_map));
            put(AppIdDef.APP_ID.GOOGLE_EMAIL, new ComponentName(PackageName.android_email, ClassName.android_email));
            put(AppIdDef.APP_ID.GOOGLE_SEARCH, new ComponentName(PackageName.google_search, ClassName.google_search));
            put(AppIdDef.APP_ID.GOOGLE_YOUTUBE, new ComponentName(PackageName.google_youtube, ClassName.google_youtube));
            put(AppIdDef.APP_ID.GOOGLE_CHROME, new ComponentName(PackageName.android_chrome, ClassName.google_chrome));
            put(AppIdDef.APP_ID.GOOGLE_PLAY_STORE, new ComponentName(PackageName.andriod_vending, ClassName.android_vending));
            put(AppIdDef.APP_ID.GOOGLE_TTS, new ComponentName(PackageName.google_tts, ""));
            put(AppIdDef.APP_ID.GOOGLE_SERVICES_FRAMEWORK, new ComponentName(PackageName.google_services_framework, ""));
            put(AppIdDef.APP_ID.GOOGLE_GMS_CORE, new ComponentName(PackageName.google_gms_core, ClassName.google_gms_core));
            put(AppIdDef.APP_ID.ANDROID_SOUND_RECORDER, new ComponentName("com.android.soundrecorder", ClassName.android_soundRecorder));
            put(AppIdDef.APP_ID.ANDROID_FILE_EXPLORE, new ComponentName(PackageName.android_document, ClassName.android_document));
            put(AppIdDef.APP_ID.ANDROID_CALCULATOR, new ComponentName(PackageName.android_calculator, ClassName.android_calculator));
            put(AppIdDef.APP_ID.ANDROID_WebView, new ComponentName(PackageName.android_webview, ClassName.android_webview));
            put(AppIdDef.APP_ID.ANDROID_Dialor, new ComponentName(PackageName.android_dialor, ClassName.android_dialor));
            put(AppIdDef.APP_ID.ORHER_GPSTEST, new ComponentName(PackageName.gps_test, ClassName.gpsTest));
            put(AppIdDef.APP_ID.OTHER_EASYCONN, new ComponentName("net.easyconn", ClassName.easyConn));
            put(AppIdDef.APP_ID.OTHER_EASYCONN_MS, new ComponentName("net.easyconn", ClassName.easyConnMs));
            put(AppIdDef.APP_ID.OTHER_EASYCONN_MS2, new ComponentName("net.easyconn", ClassName.easyConnMs2));
            put(AppIdDef.APP_ID.OTHER_ZEROTIER, new ComponentName(PackageName.zerotier, ClassName.zerotier));
            put(AppIdDef.APP_ID.OTHER_ES_EXPLORE, new ComponentName(PackageName.esFile, ClassName.esFile));
            put(AppIdDef.APP_ID.OTHER_SPOTIFY, new ComponentName(PackageName.spotify, ClassName.spotify));
            put(AppIdDef.APP_ID.OTHER_KUWO, new ComponentName(PackageName.kuwo, ClassName.kuwo));
            put(AppIdDef.APP_ID.OTHER_XIMALAYA, new ComponentName(PackageName.xmly_car, ClassName.xmly_car));
            put(AppIdDef.APP_ID.OTHER_TXZ, new ComponentName(PackageName.txz_adapter, ClassName.txz_adapter_ui));
            put(AppIdDef.APP_ID.MS_SANY_KC, new ComponentName(PackageName.ms_kc, ClassName.ms_kc));
            put(AppIdDef.APP_ID.MS_HANDBOOK_KS, new ComponentName(PackageName.ms_handbook_ks, "com.artifex.mupdfdemo.main.MuPDFActivity"));
            put(AppIdDef.APP_ID.MS_HANDBOOK_UPKEEP, new ComponentName(PackageName.ms_handbook_upkeep, "com.artifex.mupdfdemo.main.MuPDFActivity"));
            put(AppIdDef.APP_ID.MS_SJS_360, new ComponentName(PackageName.ms_sjs, ClassName.ms_sjs));
            put(AppIdDef.APP_ID.NAVI_WAZE, new ComponentName(PackageName.waze, ClassName.waze));
            put(AppIdDef.APP_ID.MO_JI, new ComponentName(PackageName.moji, ClassName.moji));
            put(AppIdDef.APP_ID.D1_LINK, new ComponentName("net.easyconn", ClassName.d1Link));
            put(AppIdDef.APP_ID.D1_CAN_BUS, new ComponentName("com.hzbhd.canbus", ClassName.d1CanBus));
            put(AppIdDef.APP_ID.INSTRUMENT, new ComponentName("com.hzbhd.canbus", ClassName.instrument));
            put(AppIdDef.APP_ID.MOTORAYALE_INFORMATION, new ComponentName("com.hzbhd.canbus", ClassName.MotorcycleInformation));
            put(AppIdDef.APP_ID.GAS_POWER_MODE, new ComponentName(PackageName.fuelElectricity, ClassName.fuelPower));
            put(AppIdDef.APP_ID.CAR_TPMS, new ComponentName("com.hzbhd.tpms.car.ui", ClassName.carTpmsActivity));
            put(AppIdDef.APP_ID.MS, new ComponentName(PackageName.msPackage, ClassName.msActivity));
            put(AppIdDef.APP_ID.TOPPPAL_SERVICE, new ComponentName("com.txznet.aipal", ClassName.toppalServiceActicity));
            put(AppIdDef.APP_ID.TOPPAL_VOICE, new ComponentName("com.txznet.smartadapter", ClassName.toppalVolceActivity));
            put(AppIdDef.APP_ID.VEHICLE_KTV, new ComponentName(PackageName.boardktv, ClassName.boardktv));
            put(AppIdDef.APP_ID.VERSATILE_THEME, new ComponentName(PackageName.theme_pack, ClassName.theme_class));
            put(AppIdDef.APP_ID.SMART_HEAVY_DUTY_TRUCK, new ComponentName(PackageName.sinotruk_pack, ClassName.sinotruk_class));
            put(AppIdDef.APP_ID.OTHER_AMAZON_PRIME_VIDEO, new ComponentName(PackageName.amazon_prime_video, ClassName.amazon_prime_video));
            put(AppIdDef.APP_ID.OTHER_APPLE_TV, new ComponentName(PackageName.apple_tv, ClassName.apple_tv));
            put(AppIdDef.APP_ID.OTHER_DISNEY, new ComponentName(PackageName.disney, ClassName.disney));
            put(AppIdDef.APP_ID.OTHER_HBO_MAX, new ComponentName(PackageName.hbo_max, ClassName.hbo_max));
            put(AppIdDef.APP_ID.OTHER_HULU, new ComponentName(PackageName.hulu, ClassName.hulu));
            put(AppIdDef.APP_ID.OTHER_NETFLIX, new ComponentName(PackageName.netflix, ClassName.netflix));
            put(AppIdDef.APP_ID.GOOGLE_YOUTUBE_TV, new ComponentName(PackageName.youtube_tv, ClassName.youtube_tv));
            put(AppIdDef.APP_ID.OTHER_PANDORA, new ComponentName(PackageName.pandora, ClassName.pandora));
            put(AppIdDef.APP_ID.OTHER_PARAMOUNTPLUS, new ComponentName(PackageName.paramount_plus, ClassName.paramount_plus));
            put(AppIdDef.APP_ID.OTHER_SUNlIGHTEN, new ComponentName(PackageName.sunlighten_pack, ClassName.sunlighten_cls));
            put(AppIdDef.APP_ID.ANDROID_SET_S5, new ComponentName("com.android.launcher3", ClassName.android_set_s5_cls));
        }
    };
    public static HashMap<AppIdDef.APP_ID, ComponentName> service = new HashMap<AppIdDef.APP_ID, ComponentName>() { // from class: com.hzbhd.commontools.DefaultAppId.2
        {
            put(AppIdDef.APP_ID.BHD_SERVICE_SETTINGS, new ComponentName(PackageName.bhd_service_setting, ClassName.bhd_service_middleware));
            put(AppIdDef.APP_ID.BHD_SERVICE_KEY, new ComponentName(PackageName.bhd_service_keydispatcher, ClassName.bhd_service_key));
            put(AppIdDef.APP_ID.BHD_SERVICE_SOURCE, new ComponentName(PackageName.bhd_service_sourcemanager, ClassName.bhd_service_source));
            put(AppIdDef.APP_ID.BHD_SERVICE_HARDWARE, new ComponentName(PackageName.bhd_service_hardware, ClassName.bhd_service_hardware));
            put(AppIdDef.APP_ID.BHD_SERVICE_FRAMEWORK, new ComponentName(PackageName.bhd_service_framework, ClassName.bhd_service_framework));
            put(AppIdDef.APP_ID.BHD_SERVICE_MCU, new ComponentName("com.hzbhd.service.mcu", ClassName.bhd_service_mcu));
            put(AppIdDef.APP_ID.BHD_SERVICE_AUDIO, new ComponentName(PackageName.bhd_service_audio, ClassName.bhd_service_audio));
            put(AppIdDef.APP_ID.BHD_SERVICE_CAMERA, new ComponentName(PackageName.bhd_service_camera, ClassName.bhd_service_camera));
            put(AppIdDef.APP_ID.BHD_SERVICE_MEDIA_SCANNER, new ComponentName(PackageName.bhd_service_mediascanner, ClassName.bhd_service_sacnner));
            put(AppIdDef.APP_ID.BHD_SERVICE_MEDIA, new ComponentName(PackageName.bhd_service_media, ClassName.bhd_service_media));
            put(AppIdDef.APP_ID.BHD_SERVICE_BLUETOOTH, new ComponentName(PackageName.bhd_service_bluetooth, ClassName.bhd_service_bt));
            put(AppIdDef.APP_ID.BHD_SERVICE_MISC, new ComponentName(PackageName.bhd_ui_misc, ClassName.bhd_service_misc));
            put(AppIdDef.APP_ID.BHD_SERVICE_CANBUS, new ComponentName("com.hzbhd.canbus", ClassName.bhd_service_canbus));
            put(AppIdDef.APP_ID.BHD_SERVICE_AUTO, new ComponentName(PackageName.bhd_auto, ClassName.bhd_service_androidauto));
            put(AppIdDef.APP_ID.BHD_SERVICE_CARPLAY, new ComponentName(PackageName.bhd_carplay, ClassName.bhd_service_carplay));
            put(AppIdDef.APP_ID.BHD_SERVICE_LOG, new ComponentName(PackageName.bhd_log, ClassName.bhd_service_log));
            put(AppIdDef.APP_ID.BHD_SERVICE_INIT, new ComponentName(PackageName.bhd_ui_misc, ClassName.bhd_service_init));
            put(AppIdDef.APP_ID.BHD_SERVICE_DISC, new ComponentName(PackageName.bhd_service_disc, ClassName.bhd_service_disc));
            put(AppIdDef.APP_ID.BHD_SERVICE_SPEECH, new ComponentName(PackageName.bhd_speech, ClassName.bhd_speech));
            put(AppIdDef.APP_ID.BHD_SERVICE_SPEECH_LYRA, new ComponentName("com.aispeech.lyra.adapter", ClassName.bhd_speech_lyra));
            put(AppIdDef.APP_ID.BHD_SERVICE_TXZ_MS, new ComponentName(PackageName.ms_bhd_speach, ClassName.ms_bhd_speach));
            put(AppIdDef.APP_ID.BHD_SERVICE_DAB, new ComponentName(PackageName.bhd_service_dab, ClassName.bhd_service_dab));
            put(AppIdDef.APP_ID.BHD_SERVICE_DVR, new ComponentName(PackageName.bhd_service_dvr, ClassName.bhd_service_dvr));
            put(AppIdDef.APP_ID.BHD_SERVICE_LCD, new ComponentName(PackageName.bhd_service_lcd, ClassName.bhd_service_lcd));
            put(AppIdDef.APP_ID.BHD_SERVICE_GYROSCOPE, new ComponentName(PackageName.bhd_service_gyroscope, ClassName.bhd_service_gyroscope));
            put(AppIdDef.APP_ID.BHD_SERVICE_UPGRADE, new ComponentName(PackageName.bhd_service_upgrade, ClassName.bhd_service_upgrade));
            put(AppIdDef.APP_ID.MS_SJS_360_DEAMON, new ComponentName(PackageName.ms_sjs_deamon, ClassName.ms_sjs_deamon));
            put(AppIdDef.APP_ID.BHD_SERVICE_LCMCUCONFIG, new ComponentName(PackageName.lcmcuconfig_pack, ClassName.lcmcuconfig_cls));
            put(AppIdDef.APP_ID.BHD_SERVICE_LCBLUETOOTH, new ComponentName(PackageName.bhd_service_lc_bluetooth, ClassName.bhd_service_lc_bluetooth));
            put(AppIdDef.APP_ID.BHD_SERVICE_SIRIUS_XM, new ComponentName(PackageName.bhd_sirius_xm, ClassName.bhd_service_sxm));
        }
    };
}
