package com.hzbhd.canbus.car._68;

import com.hzbhd.midware.constant.HotKeyConstant;
import java.util.HashMap;

/* loaded from: classes2.dex */
public class ConstantHashMap {
    public static HashMap<Integer, Integer> panelKeyMaps = new HashMap<>();
    public static HashMap<Integer, Integer> panelKeyMaps_Encore_ = new HashMap<>();
    public static HashMap<Integer, Integer> panelKeyMaps_Gl8 = new HashMap<>();

    static {
        panelKeyMaps.put(0, 0);
        panelKeyMaps.put(1, Integer.valueOf(HotKeyConstant.K_SLEEP));
        panelKeyMaps.put(2, 21);
        panelKeyMaps.put(3, 20);
        HashMap<Integer, Integer> map = panelKeyMaps;
        Integer numValueOf = Integer.valueOf(HotKeyConstant.K_CAN_CONFIG);
        map.put(4, numValueOf);
        panelKeyMaps.put(5, 4);
        panelKeyMaps.put(6, 50);
        panelKeyMaps.put(7, 62);
        panelKeyMaps.put(8, 130);
        panelKeyMaps.put(9, 3);
        panelKeyMaps.put(10, 33);
        panelKeyMaps.put(11, 34);
        panelKeyMaps.put(12, 35);
        panelKeyMaps.put(13, 36);
        panelKeyMaps.put(14, 37);
        panelKeyMaps.put(15, 38);
        panelKeyMaps.put(17, 31);
        panelKeyMaps.put(18, numValueOf);
        panelKeyMaps.put(19, Integer.valueOf(HotKeyConstant.K_TIME));
        panelKeyMaps.put(20, 62);
        panelKeyMaps.put(21, 75);
        panelKeyMaps.put(22, 49);
        panelKeyMaps.put(23, 7);
        panelKeyMaps.put(24, 8);
        panelKeyMaps.put(25, 47);
        panelKeyMaps.put(26, 48);
        panelKeyMaps.put(27, 17);
        panelKeyMaps.put(28, 45);
        panelKeyMaps.put(29, 46);
        panelKeyMaps.put(30, 47);
        panelKeyMaps.put(31, 48);
        panelKeyMaps.put(52, 65);
        panelKeyMaps.put(53, 66);
        panelKeyMaps.put(64, 141);
        panelKeyMaps.put(65, 68);
        panelKeyMaps.put(67, 128);
        panelKeyMaps.put(80, 52);
        panelKeyMaps.put(81, 2);
        panelKeyMaps.put(83, 151);
        panelKeyMaps.put(84, 59);
        panelKeyMaps.put(96, 63);
        panelKeyMaps_Encore_.put(0, 0);
        panelKeyMaps_Encore_.put(1, 34);
        panelKeyMaps_Encore_.put(2, 3);
        panelKeyMaps_Encore_.put(3, 50);
        panelKeyMaps_Encore_.put(4, 129);
        panelKeyMaps_Encore_.put(5, 62);
        panelKeyMaps_Encore_.put(6, 21);
        panelKeyMaps_Encore_.put(7, Integer.valueOf(HotKeyConstant.K_SLEEP));
        panelKeyMaps_Encore_.put(8, 49);
        panelKeyMaps_Encore_.put(9, numValueOf);
        panelKeyMaps_Encore_.put(10, 35);
        panelKeyMaps_Encore_.put(11, 36);
        panelKeyMaps_Encore_.put(12, 37);
        panelKeyMaps_Encore_.put(13, 38);
        panelKeyMaps_Encore_.put(16, 129);
        panelKeyMaps_Encore_.put(17, 31);
        panelKeyMaps_Encore_.put(18, numValueOf);
        panelKeyMaps_Encore_.put(19, Integer.valueOf(HotKeyConstant.K_TIME));
        panelKeyMaps_Encore_.put(20, 4);
        panelKeyMaps_Encore_.put(21, 33);
        panelKeyMaps_Encore_.put(22, 20);
        panelKeyMaps_Encore_.put(23, 7);
        panelKeyMaps_Encore_.put(24, 8);
        panelKeyMaps_Encore_.put(25, 47);
        panelKeyMaps_Encore_.put(26, 48);
        panelKeyMaps_Encore_.put(27, 17);
        panelKeyMaps_Encore_.put(64, 141);
        panelKeyMaps_Encore_.put(54, 130);
        panelKeyMaps_Gl8.put(0, 0);
        panelKeyMaps_Gl8.put(1, 21);
        panelKeyMaps_Gl8.put(2, 37);
        panelKeyMaps_Gl8.put(3, 36);
        panelKeyMaps_Gl8.put(4, 35);
        panelKeyMaps_Gl8.put(5, Integer.valueOf(HotKeyConstant.K_SLEEP));
        panelKeyMaps_Gl8.put(6, numValueOf);
        panelKeyMaps_Gl8.put(7, 129);
        panelKeyMaps_Gl8.put(8, 33);
        panelKeyMaps_Gl8.put(9, 34);
        panelKeyMaps_Gl8.put(10, 20);
        panelKeyMaps_Gl8.put(11, 49);
        panelKeyMaps_Gl8.put(12, 50);
        panelKeyMaps_Gl8.put(13, 4);
        panelKeyMaps_Gl8.put(14, 31);
        panelKeyMaps_Gl8.put(17, numValueOf);
        panelKeyMaps_Gl8.put(18, 59);
        panelKeyMaps_Gl8.put(19, 17);
        panelKeyMaps_Gl8.put(20, 62);
        panelKeyMaps_Gl8.put(21, 3);
        panelKeyMaps_Gl8.put(22, 38);
        panelKeyMaps_Gl8.put(23, 7);
        panelKeyMaps_Gl8.put(24, 8);
        panelKeyMaps_Gl8.put(25, 47);
        panelKeyMaps_Gl8.put(26, 48);
        panelKeyMaps_Gl8.put(52, 65);
        panelKeyMaps_Gl8.put(53, 66);
        panelKeyMaps_Gl8.put(80, 52);
        panelKeyMaps_Gl8.put(96, 68);
    }
}
