package com.hzbhd.canbus.ui_datas;

import com.hzbhd.canbus.ui_set.AirBtnAction;
import org.json.JSONException;
import org.json.JSONObject;

/* loaded from: classes2.dex */
public class GeneralAirData {
    public static boolean ac = false;
    public static boolean ac_auto = false;
    public static int ac_econ = 0;
    public static boolean ac_max = false;
    public static boolean amb = false;
    public static boolean aqs = false;
    public static boolean auto = false;
    public static int auto_1_2 = 0;
    public static boolean auto_2 = false;
    public static boolean auto_cycle = false;
    public static boolean auto_defog = false;
    public static boolean auto_manual = false;
    public static boolean auto_wind_light = false;
    public static int auto_wind_lv = 0;
    public static boolean auto_wind_strong = false;
    public static boolean big_wind_light = false;
    public static boolean blow_negative = false;
    public static boolean blow_positive = false;
    public static String center_wheel = "";
    public static boolean clean_air = false;
    public static boolean climate = false;
    public static int cycle_in_out_close = 0;
    public static boolean dual = false;
    public static boolean eco = false;
    public static boolean econ = false;
    public static boolean fahrenheit_celsius = false;
    public static boolean fast = false;
    public static boolean front_auto_wind_model = false;
    public static boolean front_auto_wind_speed = false;
    public static boolean front_defog = false;
    public static boolean front_left_auto_wind = false;
    public static boolean front_left_blow_foot = false;
    public static boolean front_left_blow_head = false;
    public static boolean front_left_blow_window = false;
    public static int front_left_seat_cold_level = 0;
    public static int front_left_seat_heat_level = 0;
    public static String front_left_temperature = "";
    public static boolean front_right_auto_wind = false;
    public static boolean front_right_auto_wind_speed = false;
    public static boolean front_right_blow_foot = false;
    public static boolean front_right_blow_head = false;
    public static boolean front_right_blow_window = false;
    public static int front_right_seat_cold_level = 0;
    public static int front_right_seat_heat_level = 0;
    public static String front_right_temperature = "";
    public static int front_right_wind_level = 0;
    public static int front_wind_level = 0;
    public static boolean front_window_heat = false;
    public static boolean hybrid_ac = false;
    public static int in_out_auto_cycle = 0;
    public static boolean in_out_cycle = false;
    public static boolean ion = false;
    public static boolean is_left_seat_heat = false;
    public static boolean is_right_seat_heat = false;
    public static boolean left_set_seat_cold = false;
    public static boolean left_set_seat_heat = false;
    public static boolean manual = false;
    public static boolean max_cool = false;
    public static boolean max_front = false;
    public static boolean max_heat = false;
    public static boolean mono = false;
    public static boolean negative_ion = false;
    public static boolean normal = false;
    public static boolean off = false;
    public static String outdoorTemperature = "";
    public static String pm_value_level_in_car = null;
    public static String pm_value_level_out_car = null;
    public static boolean pollrn_removal = false;
    public static boolean positive_sequence = false;
    public static boolean power = false;
    public static boolean rear = false;
    public static boolean rear_ac = false;
    public static boolean rear_auto = false;
    public static boolean rear_auto_wind_model = false;
    public static boolean rear_auto_wind_speed = false;
    public static boolean rear_defog = false;
    public static boolean rear_dual = false;
    public static boolean rear_left_auto_wind = false;
    public static boolean rear_left_blow_foot = false;
    public static boolean rear_left_blow_head = false;
    public static boolean rear_left_blow_window = false;
    public static int rear_left_seat_cold_level = 0;
    public static int rear_left_seat_heat_level = 0;
    public static String rear_left_temperature = "";
    public static boolean rear_lock = false;
    public static boolean rear_power = false;
    public static boolean rear_right_auto_wind = false;
    public static boolean rear_right_blow_foot = false;
    public static boolean rear_right_blow_head = false;
    public static boolean rear_right_blow_window = false;
    public static int rear_right_seat_cold_level = 0;
    public static int rear_right_seat_heat_level = 0;
    public static String rear_right_temperature = "";
    public static boolean rear_sync = false;
    public static String rear_temperature = "";
    public static int rear_wind_level = 0;
    public static boolean rest = false;
    public static boolean reverse_order = false;
    public static boolean right_set_seat_cold = false;
    public static boolean right_set_seat_heat = false;
    public static boolean seat_steering_wheel_synchronization = false;
    public static boolean small_wind_light = false;
    public static boolean soft = false;
    public static boolean steering_wheel_heating = false;
    public static boolean swing = false;
    public static boolean sync = false;
    public static boolean sync_temperature = false;
    public static boolean threeZone = false;
    public static boolean windshield_deicing = false;

    public static String getAirInfo() throws JSONException {
        JSONObject jSONObject = new JSONObject();
        try {
            jSONObject.put("power", power);
            jSONObject.put("ac", ac);
            jSONObject.put(AirBtnAction.AC_AUTO, ac_auto);
            jSONObject.put(AirBtnAction.AC_MAX, ac_max);
            jSONObject.put(AirBtnAction.AMB, amb);
            jSONObject.put("auto", auto);
            jSONObject.put(AirBtnAction.AUTO_2, auto_2);
            jSONObject.put("dual", dual);
            jSONObject.put("in_out_cycle", in_out_cycle);
            jSONObject.put(AirBtnAction.AQS, aqs);
            jSONObject.put("front_defog", front_defog);
            jSONObject.put("rear_defog", rear_defog);
            jSONObject.put(AirBtnAction.REAR_POWER, rear_power);
            jSONObject.put(AirBtnAction.REAR_LOCK, rear_lock);
            jSONObject.put(AirBtnAction.ECO, eco);
            jSONObject.put(AirBtnAction.ECON, econ);
            jSONObject.put(AirBtnAction.AC_ECON, ac_econ);
            jSONObject.put(AirBtnAction.CLIMATE, climate);
            jSONObject.put(AirBtnAction.SYNC_TEMPERATURE, sync_temperature);
            jSONObject.put("sync", sync);
            jSONObject.put(AirBtnAction.MAX_COOL, max_cool);
            jSONObject.put(AirBtnAction.ION, ion);
            jSONObject.put(AirBtnAction.LEFT_SET_SEAT_HEAT, left_set_seat_heat);
            jSONObject.put(AirBtnAction.RIGHT_SET_SEAT_HEAT, right_set_seat_heat);
            jSONObject.put(AirBtnAction.LEFT_SET_SEAT_COLD, left_set_seat_cold);
            jSONObject.put(AirBtnAction.RIGHT_SET_SEAT_COLD, right_set_seat_cold);
            jSONObject.put(AirBtnAction.IN_OUT_AUTO_CYCLE, in_out_auto_cycle);
            jSONObject.put("positive_sequence", positive_sequence);
            jSONObject.put("reverse_order", reverse_order);
            jSONObject.put(AirBtnAction.AUTO_CYCLE, auto_cycle);
            jSONObject.put(AirBtnAction.CLEAN_AIR, clean_air);
            jSONObject.put(AirBtnAction.STEERING_WHEEL_HEATING, steering_wheel_heating);
            jSONObject.put(AirBtnAction.SEAT_STEERING_WHEEL_SYNCHRONIZATION, seat_steering_wheel_synchronization);
            jSONObject.put(AirBtnAction.REAR_AUTO, rear_auto);
            jSONObject.put(AirBtnAction.AUTO_WIND_LV, auto_wind_lv);
            jSONObject.put(AirBtnAction.MAX_HEAT, max_heat);
            jSONObject.put(AirBtnAction.FRONT_WINDOW_HEAT, front_window_heat);
            jSONObject.put(AirBtnAction.BIG_WIND_LIGHT, big_wind_light);
            jSONObject.put(AirBtnAction.SMALL_WIND_LIGHT, small_wind_light);
            jSONObject.put(AirBtnAction.MAX_FRONT, max_front);
            jSONObject.put(AirBtnAction.REAR, rear);
            jSONObject.put("front_auto_wind_model", front_auto_wind_model);
            jSONObject.put("rear_auto_wind_model", rear_auto_wind_model);
            jSONObject.put("front_left_blow_window", front_left_blow_window);
            jSONObject.put("front_left_blow_head", front_left_blow_head);
            jSONObject.put("front_left_blow_foot", front_left_blow_foot);
            jSONObject.put("front_left_auto_wind", front_left_auto_wind);
            jSONObject.put("front_right_blow_window", front_right_blow_window);
            jSONObject.put("front_right_blow_head", front_right_blow_head);
            jSONObject.put("front_right_blow_foot", front_right_blow_foot);
            jSONObject.put("front_right_auto_wind", front_right_auto_wind);
            jSONObject.put("rear_left_blow_window", rear_left_blow_window);
            jSONObject.put("rear_left_blow_head", rear_left_blow_head);
            jSONObject.put("rear_left_blow_foot", rear_left_blow_foot);
            jSONObject.put("rear_left_auto_wind", rear_left_auto_wind);
            jSONObject.put("rear_right_blow_window", rear_right_blow_window);
            jSONObject.put("rear_right_blow_head", rear_right_blow_head);
            jSONObject.put("rear_right_blow_foot", rear_right_blow_foot);
            jSONObject.put("rear_right_auto_wind", rear_right_auto_wind);
            jSONObject.put("front_left_temperature", front_left_temperature);
            jSONObject.put("front_right_temperature", front_right_temperature);
            jSONObject.put("rear_left_temperature", rear_left_temperature);
            jSONObject.put("rear_right_temperature", rear_right_temperature);
            jSONObject.put("rear_temperature", rear_temperature);
            jSONObject.put("center_wheel", center_wheel);
            jSONObject.put("front_wind_level", front_wind_level);
            jSONObject.put("front_auto_wind_speed", front_auto_wind_speed);
            jSONObject.put("front_right_wind_level", front_right_wind_level);
            jSONObject.put("front_right_auto_wind_speed", front_right_auto_wind_speed);
            jSONObject.put("rear_wind_level", rear_wind_level);
            jSONObject.put("rear_auto_wind_speed", rear_auto_wind_speed);
            jSONObject.put("front_left_seat_heat_level", front_left_seat_heat_level);
            jSONObject.put("front_right_seat_heat_level", front_right_seat_heat_level);
            jSONObject.put("rear_left_seat_heat_level", rear_left_seat_heat_level);
            jSONObject.put("rear_right_seat_heat_level", rear_right_seat_heat_level);
            jSONObject.put("front_left_seat_cold_level", front_left_seat_cold_level);
            jSONObject.put("front_right_seat_cold_level", front_right_seat_cold_level);
            jSONObject.put("rear_left_seat_cold_level", rear_left_seat_cold_level);
            jSONObject.put("rear_right_seat_cold_level", rear_right_seat_cold_level);
            jSONObject.put("pm_value_level_in_car", pm_value_level_in_car);
            jSONObject.put("pm_value_level_out_car", pm_value_level_out_car);
            jSONObject.put("blow_positive", blow_positive);
            jSONObject.put(AirBtnAction.BLOW_NEGATIVE, blow_negative);
            jSONObject.put("fahrenheit_celsius", fahrenheit_celsius);
            jSONObject.put(AirBtnAction.MANUAL, manual);
            jSONObject.put(AirBtnAction.MONO, mono);
            jSONObject.put(AirBtnAction.AUTO_DEFOG, auto_defog);
            jSONObject.put(AirBtnAction.AUTO_WIND_STRONG, auto_wind_strong);
            jSONObject.put(AirBtnAction.AUTO_WIND_LIGHT, auto_wind_light);
            jSONObject.put(AirBtnAction.AUTO_MANUAL, auto_manual);
            jSONObject.put(AirBtnAction.SWING, swing);
            jSONObject.put(AirBtnAction.WINDSHIELD_DEICING, windshield_deicing);
            jSONObject.put(AirBtnAction.POLLRN_REMOVAL, pollrn_removal);
            jSONObject.put(AirBtnAction.CYCLE_IN_OUT_CLOSE, cycle_in_out_close);
            jSONObject.put(AirBtnAction.SOFT, soft);
            jSONObject.put(AirBtnAction.FAST, fast);
            jSONObject.put(AirBtnAction.NORMAL, normal);
            jSONObject.put("threeZone", threeZone);
            jSONObject.put(AirBtnAction.REST, rest);
            jSONObject.put("is_left_seat_heat", is_left_seat_heat);
            jSONObject.put("is_right_seat_heat", is_right_seat_heat);
            jSONObject.put(AirBtnAction.NEGATIVE_ION, negative_ion);
            jSONObject.put(AirBtnAction.REAR_SYNC, rear_sync);
            jSONObject.put(AirBtnAction.HYBRID_AC, hybrid_ac);
        } catch (JSONException e) {
            e.printStackTrace();
        }
        return jSONObject.toString();
    }
}
